#!/usr/bin/env bash
set -e

IMAGE_NAME="pietro"

docker-image-build \
	$IMAGE_NAME \
	--build-arg USER_NAME="$USER" \
	--build-arg USER_ID="$(id -u)" \
	--stage dev

docker-run-interactive \
	"${IMAGE_NAME}-dev" \
	--volume .:/app
