#!/usr/bin/env bash
# This script will launch a local Docker image similar to what will be spawned
# on CircleCi. Use this to troubleshoot build errors, such as missing
# executable (xpdf, ghostscript, etc)
set -e

# We need to pass to the Dockerfile the user name and uid, so we can replicate
# the same user in the container
HOST_UID="$(id -u)"
HOST_USER="$USER"
COMMAND_ARGS="$*"

export HOST_UID
export HOST_USER
export COMMAND_ARGS

docker-compose build simulate-circleci
docker-compose run --rm simulate-circleci
